### ISSUE TITLE
500!

### ISSUE THREAD

**Issue by AliMD** [AliMD/vatr#65]

**Comment by mmohammadi** [comment]
استاد سلام خوبین؟ کیش خوش گذشت؟ پارسال توی کیش دیدمتون داشتین دوچرخه سواری میکردین اومدم سلام کنم بهتون مامانم گفت نرو زشته :)))

**Comment by omidgharib** [comment]
@AliMD عشقی

**Comment by ahmaddehnavi** [comment]
سلام به همگی
امیدوارم حال همگیتون خوب باشه 
ده سال از باز شدن این issue گذشته و وقتی بهش فکر میکنم انگار همین دیروز بود که دانشجو بودیم
پیشاپیش عیدتون هم مبارک

**Comment by AliMD** [comment]
@mmohammadi @omidgharib @ahmaddehnavi 
به به
سلام و عرض ادب
دوستان قدیم
من داستان آموزش رو ۱۰ سال به تاخیر انداختم که به روز بشم
و الان به بهانه این پروژه دوباره شروع کردم و کلی حرف دارم

تو گفتگو پروژه ادامه بدیم
https://github.com/AliMD/alwatr/discussions
فعلا یک کوچولو چند تا پکیج رو نوشتم و توضیح دادم ولی کلی برنامه دارم انشاالله
