### ISSUE TITLE
Arrow function replacement for string replace

### ISSUE THREAD

**Issue by MM25Zamanian** [AliMD/vatr#82]
Wouldn't it be better to use the arrow functions [here](https://github.com/AliMD/vatr/blob/next/package/logger/src/logger.ts#L113)?

**Comment by AliMD** [comment]
Which line exactly?!
All functions are arrow!

**Comment by AliMD** [comment]
در ضمن این که تایپی از ایشو هستش؟!
لطفا اگر ایشو (مشکل) نیست دیسکاشن باز کن

**Comment by AliMD** [comment]
الان دیسکاشنی که تبدیل کردی کجاست؟
بعد تبدیل پاکش کردی؟ 😆

**Comment by AliMD** [comment]
من متوجه اینکه چطور باید اونجا arrow باشه نمیشم کد نمونه بده
ولی جدا از این بحث چرا هر دفعه داره replace میشه! لطفا قبل return یک بریز تو متغییر styleScope و داخل ازش استفاده کن
مرسی

**Comment by MM25Zamanian** [comment]
> الان دیسکاشنی که تبدیل کردی کجاست؟
> بعد تبدیل پاکش کردی؟ 😆 
> 

من اشتباه کرده بودم

**Comment by MM25Zamanian** [comment]
واسه همین پاکش کردم ولی قبلش به دیسکاشن تبدیل کردم
